dependency check added to install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,5 +1,23 @@
 #!/bin/bash
+echo "checking if all dependencies are installed..."
+echo ""
+rm -f ./missing
+for PROG in {autorandr,betterlockscreen,bspwm,dmenu,dunst,dunstify,feh,flameshot,jshon,networkmanager_dmenu,numlockx,picom,playerctl,polybar,rofi,sxhkd,xterm}; do
+    if ! command -v $PROG >/dev/null
+    then
+        echo $PROG >> ./missing
+    fi
+done
 
-rsync -av --progress config/* /home/$USER/.config/
-rsync -av --progress .??* /home/$USER/ --exclude .git
-xrdb -merge ~/.Xresources
+if ! [ -f "./missing" ]; then
+    echo all dependencies met
+    rsync -av --progress config/* /home/$USER/.config/
+    rsync -av --progress .??* /home/$USER/ --exclude .git
+    xrdb -merge ~/.Xresources
+else
+    echo "Missing dependencies: "
+    while read -r line; do
+        echo $line
+    done < ./missing
+    
+fi
